In [1]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier

In [2]:
file_name_x= "train/x_train.csv"
data_x = pd.read_csv(file_name_x)
data_x = data_x.groupby(['GeneId']).mean()
data_x = pd.DataFrame(data_x).reset_index()
fea = ['H3K4me3', 'H3K4me1', 'H3K36me3','H3K9me3','H3K27me3',]
data_x = data_x[fea]
#data_x

In [3]:
file_name_y= "train/y_train.csv"
data_y = pd.read_csv(file_name_y)
data_y = data_y['Prediction']
#data_y

In [4]:
  forestModel = RandomForestClassifier()

In [5]:
forestModel.fit(data_x, data_y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [6]:
file_name_x= "test/x_test.csv"
data_x = pd.read_csv(file_name_x)
data_x = data_x.groupby(['GeneId']).mean()
data_x = pd.DataFrame(data_x).reset_index()
fea = ['H3K4me3', 'H3K4me1', 'H3K36me3','H3K9me3','H3K27me3',]
data_x = data_x[fea]

In [7]:
y_predict = pd.DataFrame(forestModel.predict(data_x))
y_predict['Prediction'] = y_predict
y_predict

      0  Prediction
0     1           1
1     0           0
2     1           1
3     0           0
4     0           0
5     1           1
6     0           0
7     0           0
8     1           1
9     0           0
10    1           1
11    1           1
12    0           0
13    0           0
14    1           1
15    1           1
16    1           1
17    1           1
18    1           1
19    0           0
20    1           1
21    0           0
22    1           1
23    0           0
24    0           0
25    1           1
26    0           0
27    0           0
28    0           0
29    1           1
...  ..         ...
3841  0           0
3842  0           0
3843  1           1
3844  1           1
3845  0           0
3846  0           0
3847  0           0
3848  1           1
3849  0           0
3850  1           1
3851  0           0
3852  0           0
3853  0           0
3854  0           0
3855  0           0
3856  0           0
3857  0           0
3858  1           1
3859  1           1
3860  1           1
3861  1           1
3862  0           0
3863  1           1
3864  1           1
3865  0           0
3866  1           1
3867  0           0
3868  1           1
3869  0           0
3870  1           1

[3871 rows x 2 columns]

In [8]:
file_name_submission= "submission.csv"
data_submission = pd.read_csv(file_name_submission)
data_submission

      GeneId  Prediction
0          1         0.0
1          2         1.0
2          3         1.0
3          4         0.0
4          5         0.0
5          6         1.0
6          7         0.0
7          8         0.0
8          9         1.0
9         10         0.0
10        11         1.0
11        12         1.0
12        13         0.0
13        14         1.0
14        15         1.0
15        16         1.0
16        17         1.0
17        18         1.0
18        19         1.0
19        20         1.0
20        21         1.0
21        22         0.0
22        23         1.0
23        24         0.0
24        25         0.0
25        26         1.0
26        27         0.0
27        28         0.0
28        29         0.0
29        30         1.0
...      ...         ...
3841    3842         0.0
3842    3843         0.0
3843    3844         1.0
3844    3845         1.0
3845    3846         0.0
3846    3847         0.0
3847    3848         0.0
3848    3849         1.0
3849    3850         0.0
3850    3851         1.0
3851    3852         1.0
3852    3853         0.0
3853    3854         0.0
3854    3855         0.0
3855    3856         0.0
3856    3857         0.0
3857    3858         0.0
3858    3859         1.0
3859    3860         1.0
3860    3861         1.0
3861    3862         1.0
3862    3863         0.0
3863    3864         1.0
3864    3865         1.0
3865    3866         0.0
3866    3867         1.0
3867    3868         0.0
3868    3869         1.0
3869    3870         0.0
3870    3871         0.0

[3871 rows x 2 columns]

In [11]:
data_submission['Prediction'] = y_predict['Prediction']
fea = ['GeneId', 'Prediction',]
data_submission = data_submission[fea]
data_submission

      GeneId  Prediction
0          1           1
1          2           0
2          3           1
3          4           0
4          5           0
5          6           1
6          7           0
7          8           0
8          9           1
9         10           0
10        11           1
11        12           1
12        13           0
13        14           0
14        15           1
15        16           1
16        17           1
17        18           1
18        19           1
19        20           0
20        21           1
21        22           0
22        23           1
23        24           0
24        25           0
25        26           1
26        27           0
27        28           0
28        29           0
29        30           1
...      ...         ...
3841    3842           0
3842    3843           0
3843    3844           1
3844    3845           1
3845    3846           0
3846    3847           0
3847    3848           0
3848    3849           1
3849    3850           0
3850    3851           1
3851    3852           0
3852    3853           0
3853    3854           0
3854    3855           0
3855    3856           0
3856    3857           0
3857    3858           0
3858    3859           1
3859    3860           1
3860    3861           1
3861    3862           1
3862    3863           0
3863    3864           1
3864    3865           1
3865    3866           0
3866    3867           1
3867    3868           0
3868    3869           1
3869    3870           0
3870    3871           1

[3871 rows x 2 columns]

In [14]:
data_submission.to_csv("result_pivi.csv", index=False)